name: EmirNicks
version: '1.1.0'
main: xyz.emirdev.emirnicks.EmirNicks
api-version: '1.21'
authors: [ EmirhanTr3 ]
loader: xyz.emirdev.emirnicks.EmirNicksPluginLoader
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
