name: EchoName
version: '1.1.0'
main: xyz.emirdev.echoname.EchoName
api-version: '1.21'
authors: [ EmirhanTr3 ]
loader: xyz.emirdev.echoname.EchoNamePluginLoader
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
